# Generated by Django 6.0.2 on 2026-02-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                ("sobrenome", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone_ddd", models.CharField(max_length=3)),
                ("telefone", models.CharField(max_length=10)),
                ("data_nascimento", models.DateField()),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("cidade", models.CharField(max_length=120)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
                ("url_foto", models.URLField()),
                ("nome", models.CharField(max_length=160)),
                ("descricao", models.TextField()),
                ("valor_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("num_estoque", models.PositiveSmallIntegerField()),
                ("sku", models.CharField(max_length=40, unique=True)),
                ("categoria", models.CharField(max_length=80)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("faturado", "Faturado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("numero_pedido", models.CharField(max_length=30, unique=True)),
                ("data_faturamento", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="api.cliente",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_alteracao", models.DateTimeField(auto_now=True)),
                ("quantidade", models.PositiveIntegerField()),
                ("valor_unitario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("observacoes", models.TextField(blank=True)),
                ("numero_item", models.PositiveSmallIntegerField(default=1)),
                ("valor_desconto", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cancelado", models.BooleanField(default=False)),
                (
                    "pedido",
                    models.ForeignKey(
                        db_column="pedido_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="api.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="produto_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_pedido",
                        to="api.produto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
