# Generated by Django 6.0.2 on 2026-02-21 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_pedido_num_pedido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="valor_total",
        ),
    ]
