# Generated by Django 6.0.2 on 2026-02-21 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_pedido_valor_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itempedido",
            name="valor_desconto",
        ),
    ]
