# Generated by Django 6.0.2 on 2026-02-22 17:42

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_itempedido_valor_desconto"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
        migrations.AddField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12),
        ),
    ]
